// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTranscript() {
  return window['go']['main']['App']['ClearTranscript']();
}

export function DeletePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePod'](arg1, arg2, arg3);
}

export function DescribePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DescribePod'](arg1, arg2, arg3);
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetPodLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2, arg3, arg4);
}

export function GetTranscript() {
  return window['go']['main']['App']['GetTranscript']();
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListNamespaces(arg1) {
  return window['go']['main']['App']['ListNamespaces'](arg1);
}

export function ListPods(arg1, arg2) {
  return window['go']['main']['App']['ListPods'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}
