// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTranscript():Promise<void>;

export function DeletePod(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function DescribePod(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function GetCurrentContext():Promise<main.CommandResult>;

export function GetPodLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.CommandResult>;

export function GetTranscript():Promise<Array<main.CommandResult>>;

export function ListContexts():Promise<main.CommandResult>;

export function ListNamespaces(arg1:string):Promise<main.CommandResult>;

export function ListPods(arg1:string,arg2:string):Promise<main.CommandResult>;

export function SetContext(arg1:string):Promise<main.CommandResult>;
